#!/usr/bin/env bash
#This bash script transfers a file from our client to a server

if [ "$#" -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  export SSHPASS='no'
  scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/$1"
fi
