#!/usr/bin/env bash

#This bash script transfers a file from our client to a server
# file use Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
if [ "$#" -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  export SSHPASS='no'
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
