#!/usr/bin/env bash
# This is a redirect script

sed -i '/listen \[::\]:80 default_server;/a\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

sudo service nginx restart
