#!/usr/bin/env bash
# This script displays numbers from 1 to 100
#+ Displays FizzBuzz when number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5
#+ Otherwise, displays the number
num1=3
num2=5
for ((i=1; i<=100; i++)); do
	if  [ "$((i % num1))" -eq 0 ] && [ "$((i % num2))" -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ "$((i % num2))" -eq 0 ]
	then
		echo "Buzz"
	elif [ "$((i % num1))" -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
