#!/usr/bin/env bash
# This scripting is displaying "Best School" 10 times and "Hi" then "Best School" 
#+ on the 9th time
i=0
while ((i<10)); do
	if [ "$i" -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
